name: Automation build test

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Install Protoc
        uses: Arduino/actions/setup-protoc@master
        with:
          version: '3.7'

      - name: Checkout latest build
        run:
          git checkout dev && git pull
          
      - name: Latest commit logs
        run:
          git log -3
          
      - name: Build test script
        run:
          dotnet restore && dotnet build
